"""
Clip generator using FFmpeg.

Pipeline per clip:
  1. Cut the source video to the clip range with `-ss`/`-to`.
  2. Apply a crop (face-centered single-person, or split-screen for
     multi-speaker).
  3. Apply an anti-copyright filter (subtle but actually noticeable
     pixel-level changes: tiny rotation + color shift + audio re-tune).
  4. Burn the ASS subtitles generated by subtitle_styles.py.
  5. Encode using NVENC when available (GTX 1650), otherwise libx264.
  6. Generate a thumbnail.

Clips are generated in parallel via a thread pool. FFmpeg already uses
all CPU/GPU resources for one encode, so we keep the pool small (2–3 for
NVENC, configurable for CPU) to avoid thrashing.
"""

from __future__ import annotations

import json
import os
import random
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed

from gpu_utils import gpu_info, video_encoder_args
from subtitle_styles import generate_word_by_word_ass
from utils import (
    emit_complete,
    emit_error,
    emit_progress,
    ensure_dirs,
    get_clip_dir,
)


# ---------------------------------------------------------------------------
# Anti-copyright filter
# ---------------------------------------------------------------------------


def _build_anticopy_video_filter(output_w: int, output_h: int, strength: str = "medium") -> str:
    """
    Build an anti-copyright video filter chain.

    Three strength levels:
      - off:    just scale to target resolution (no fingerprint at all)
      - light:  tiny color shift (invisible, fools simple hash matchers)
      - medium: color shift + 1-2px crop pad + tiny rotation (~0.3°)
      - strong: medium + mirror horizontally (visible difference)

    All variants finish by scaling to (output_w, output_h) with lanczos.
    """
    if strength == "off":
        return f"scale={output_w}:{output_h}:flags=lanczos"

    brightness = round(random.uniform(-0.025, 0.025), 4)
    contrast = round(random.uniform(0.97, 1.03), 4)
    saturation = round(random.uniform(0.94, 1.06), 4)
    # Tiny gamma shift further changes pixel histograms without being visible
    gamma = round(random.uniform(0.97, 1.03), 4)

    eq = f"eq=brightness={brightness}:contrast={contrast}:saturation={saturation}:gamma={gamma}"

    if strength == "light":
        return f"scale={output_w}:{output_h}:flags=lanczos,{eq}"

    # medium / strong both apply micro rotation + slight padding crop.
    # Rotation is so small it's invisible but breaks hash-based fingerprinting.
    rot = round(random.uniform(-0.35, 0.35) * 3.14159 / 180, 6)  # ±0.35°
    pad_px = random.randint(2, 6)

    # rotate -> tiny crop (to hide black corners) -> eq -> scale
    chain = (
        f"rotate={rot}:fillcolor=black,"
        f"crop=iw-{pad_px * 2}:ih-{pad_px * 2}:{pad_px}:{pad_px},"
        f"{eq},"
        f"scale={output_w}:{output_h}:flags=lanczos"
    )

    if strength == "strong":
        chain = f"hflip,{chain}"

    return chain


def _build_anticopy_audio_args(strength: str = "medium") -> list[str]:
    """
    Build an FFmpeg audio filter argument list that subtly re-pitches audio.

    Strength levels:
      - off:    no audio filter (re-encode only)
      - light:  ±10–25 cents pitch shift via `asetrate` (sub-perceptible)
      - medium: ±25–40 cents
      - strong: ±40–60 cents
    """
    if strength == "off":
        return []

    cents_ranges = {
        "light": (10, 25),
        "medium": (25, 40),
        "strong": (40, 60),
    }
    low, high = cents_ranges.get(strength, cents_ranges["medium"])
    cents = random.randint(low, high) * random.choice([-1, 1])
    ratio = 2 ** (cents / 1200)  # pitch ratio for `cents` cents

    # asetrate changes both pitch + speed; atempo undoes the speed change.
    # We must split atempo across multiple stages if ratio is outside [0.5, 2].
    # For ±60 cents, ratio is well within [0.5, 2], so a single atempo works.
    sample_rate = 48000
    new_rate = int(sample_rate * ratio)
    af = f"asetrate={new_rate},aresample={sample_rate},atempo={1/ratio:.6f}"

    return ["-af", af]


# ---------------------------------------------------------------------------
# Subtitle path escaping for FFmpeg's ass= filter
# ---------------------------------------------------------------------------


def _safe_ass_path(sub_path: str) -> str:
    """
    Convert a path to FFmpeg `ass=` filter safe format.

    On Windows, drive-letter colons confuse FFmpeg's filter parser, so we
    prefer a relative path from cwd. Spaces and remaining colons are
    backslash-escaped.
    """
    try:
        cwd = os.getcwd()
        rel_path = os.path.relpath(sub_path, cwd)
        safe = rel_path.replace('\\', '/')
    except ValueError:
        # Different drive — fall back to absolute path
        safe = sub_path.replace('\\', '/')

    safe = safe.replace(':', '\\:')
    safe = safe.replace(' ', '\\ ')
    return safe


# ---------------------------------------------------------------------------
# Single clip generation
# ---------------------------------------------------------------------------


def generate_single_clip(
    video_path: str,
    clip: dict,
    output_dir: str,
    transcription: dict = None,
    template: str = "default",
    add_subtitles: bool = True,
    hook_position: str = "upper",
    sub_position: str = "bottom",
    anticopy_strength: str = "medium",
    quality: str = "balanced",
) -> dict:
    """
    Generate a single short clip from the original video.

    Supports:
      - Single-person face-centered crop.
      - Multi-speaker split-screen (top/bottom).
      - Anti-copyright video + audio fingerprint.
      - Subtitle burning.
      - GPU-accelerated encoding via NVENC when available.
    """
    clip_index = clip['index']
    start = clip['start']
    end = clip['end']
    duration = clip['duration']
    crop = clip.get('crop', {})
    split_crop = clip.get('split_crop', None)

    output_path = os.path.join(output_dir, f"clip_{clip_index:03d}.mp4")
    thumb_path = os.path.join(output_dir, f"clip_{clip_index:03d}_thumb.jpg")
    sub_path = os.path.join(output_dir, f"clip_{clip_index:03d}.ass")

    out_w = crop.get('output_w', 1080) if crop else 1080
    out_h = crop.get('output_h', 1920) if crop else 1920

    is_split = split_crop is not None and split_crop.get('mode') == 'split'

    if is_split:
        out_w = split_crop['output_w']
        out_h = split_crop['output_h']

    encoder_args = video_encoder_args(quality=quality)

    # Build the ASS file ahead of time so we can reference it from either
    # filter graph (split vs single).
    subtitle_filter_segment: str | None = None
    if add_subtitles and transcription and transcription.get('words'):
        clip_words = [
            w for w in transcription['words']
            if w['start'] >= start - 0.5 and w['end'] <= end + 0.5
        ]
        if clip_words:
            ass_content = generate_word_by_word_ass(
                clip_words, start, template, out_w, out_h,
                clip_duration=duration,
                hook_position=hook_position, sub_position=sub_position,
            )
            with open(sub_path, 'w', encoding='utf-8') as f:
                f.write(ass_content)
            subtitle_filter_segment = f"ass={_safe_ass_path(sub_path)}"

    if is_split:
        # ===== SPLIT-SCREEN MODE =====
        tc = split_crop['top_crop']
        bc = split_crop['bottom_crop']
        half_h = split_crop['half_h']

        top_anticopy = _build_anticopy_video_filter(out_w, half_h, anticopy_strength)
        bottom_anticopy = _build_anticopy_video_filter(out_w, half_h, anticopy_strength)

        filter_complex = (
            f"[0:v]crop={tc['w']}:{tc['h']}:{tc['x']}:{tc['y']},"
            f"{top_anticopy}[top];"
            f"[0:v]crop={bc['w']}:{bc['h']}:{bc['x']}:{bc['y']},"
            f"{bottom_anticopy}[bottom];"
            f"color=c=white:s={out_w}x4[line];"
            f"[top][line][bottom]vstack=inputs=3,scale={out_w}:{out_h}[v]"
        )

        if subtitle_filter_segment is not None:
            filter_complex += f";[v]{subtitle_filter_segment}[vout]"
            output_label = "[vout]"
        else:
            output_label = "[v]"

        cmd = [
            'ffmpeg', '-y',
            '-ss', str(start),
            '-to', str(end),
            '-i', video_path,
            '-filter_complex', filter_complex,
            '-map', output_label,
            '-map', '0:a?',
            *encoder_args,
            '-c:a', 'aac',
            '-b:a', '128k',
            *_build_anticopy_audio_args(anticopy_strength),
            '-movflags', '+faststart',
            '-shortest',
            output_path,
        ]

    else:
        # ===== SINGLE-PERSON MODE =====
        filters = []

        if crop:
            cx = crop.get('x', 0)
            cy = crop.get('y', 0)
            cw = crop.get('w', 1080)
            ch = crop.get('h', 1920)
            filters.append(f"crop={cw}:{ch}:{cx}:{cy}")
        else:
            filters.append("crop=ih*9/16:ih:(iw-ih*9/16)/2:0")

        filters.append(_build_anticopy_video_filter(out_w, out_h, anticopy_strength))

        if subtitle_filter_segment is not None:
            filters.append(subtitle_filter_segment)

        filter_str = ','.join(filters)

        cmd = [
            'ffmpeg', '-y',
            '-ss', str(start),
            '-to', str(end),
            '-i', video_path,
            '-vf', filter_str,
            *encoder_args,
            '-c:a', 'aac',
            '-b:a', '128k',
            *_build_anticopy_audio_args(anticopy_strength),
            '-movflags', '+faststart',
            '-shortest',
            output_path,
        ]

    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=900,
        )

        if result.returncode != 0:
            stderr_tail = result.stderr[-400:] if result.stderr else 'unknown'
            print(
                f"[CLIP {clip_index}] FFmpeg FAILED ({_short_encoder_name(encoder_args)}). "
                f"Error: {stderr_tail}",
                flush=True,
            )

            # Retry with CPU encoder + no subtitle (most common failure cause)
            fallback_filters = []
            if crop:
                cx = crop.get('x', 0)
                cy = crop.get('y', 0)
                cw = crop.get('w', 1080)
                ch = crop.get('h', 1920)
                fallback_filters.append(f"crop={cw}:{ch}:{cx}:{cy}")
            else:
                fallback_filters.append("crop=ih*9/16:ih:(iw-ih*9/16)/2:0")
            fallback_filters.append(f"scale={out_w}:{out_h}")

            cmd_retry = [
                'ffmpeg', '-y',
                '-ss', str(start),
                '-to', str(end),
                '-i', video_path,
                '-vf', ','.join(fallback_filters),
                '-c:v', 'libx264', '-preset', 'veryfast', '-crf', '25',
                '-pix_fmt', 'yuv420p',
                '-c:a', 'aac', '-b:a', '128k',
                '-movflags', '+faststart', '-shortest',
                output_path,
            ]

            retry = subprocess.run(cmd_retry, capture_output=True, text=True, timeout=600)
            if retry.returncode != 0:
                return None

        # Thumbnail at 1/3 of the way through the clip
        thumb_cmd = [
            'ffmpeg', '-y',
            '-ss', str(start + duration / 3),
            '-i', video_path,
        ]

        if is_split and split_crop:
            tc = split_crop['top_crop']
            thumb_cmd.extend(['-vf', f"crop={tc['w']}:{tc['h']}:{tc['x']}:{tc['y']},scale=270:480"])
        elif crop:
            cx = crop.get('x', 0)
            cy = crop.get('y', 0)
            cw = crop.get('w', 1080)
            ch = crop.get('h', 1920)
            thumb_cmd.extend(['-vf', f"crop={cw}:{ch}:{cx}:{cy},scale=270:480"])
        else:
            thumb_cmd.extend(['-vf', "crop=ih*9/16:ih:(iw-ih*9/16)/2:0,scale=270:480"])

        thumb_cmd.extend(['-vframes', '1', '-q:v', '3', thumb_path])
        subprocess.run(thumb_cmd, capture_output=True, text=True, timeout=30)

        file_size = os.path.getsize(output_path) if os.path.exists(output_path) else 0

        clip['output_path'] = output_path
        clip['thumbnail_path'] = thumb_path if os.path.exists(thumb_path) else None
        clip['subtitle_path'] = sub_path if os.path.exists(sub_path) else None
        clip['file_size'] = file_size
        clip['generated'] = True
        clip['is_split_screen'] = is_split
        clip['encoder'] = _short_encoder_name(encoder_args)

        return clip

    except subprocess.TimeoutExpired:
        return None
    except Exception:  # noqa: BLE001
        return None


def _short_encoder_name(encoder_args: list[str]) -> str:
    """Extract a short readable encoder tag from FFmpeg args."""
    try:
        idx = encoder_args.index("-c:v")
        return encoder_args[idx + 1]
    except (ValueError, IndexError):
        return "libx264"


# ---------------------------------------------------------------------------
# Batch generation with thread pool
# ---------------------------------------------------------------------------


def _default_worker_count() -> int:
    """
    Choose a sensible parallelism level.

    NVENC handles ~2 simultaneous H.264 encodes well on consumer cards
    (GTX 1650 = 1 NVENC chip, but the kernel queues sessions); going
    higher won't help.

    libx264 already uses all CPU cores for one encode, so 2 workers is a
    safe upper bound to avoid context-switching thrash.
    """
    override = os.environ.get("LTS_CLIP_WORKERS")
    if override:
        try:
            return max(1, int(override))
        except ValueError:
            pass

    info = gpu_info()
    return 2 if info["nvenc"].get("available") else 2


def generate_all_clips(
    video_path: str,
    clips: list,
    video_id: str,
    transcription: dict = None,
    template: str = "default",
    add_subtitles: bool = True,
    hook_position: str = "upper",
    sub_position: str = "bottom",
    anticopy_strength: str = "medium",
    quality: str = "balanced",
    workers: int | None = None,
) -> list:
    """
    Generate all clips from a video. Uses a thread pool for concurrent encodes.
    """
    ensure_dirs()
    output_dir = get_clip_dir(video_id)

    info = gpu_info()
    n_workers = workers if workers is not None else _default_worker_count()

    emit_progress(
        "generate", 0,
        f"Generating {len(clips)} clips "
        f"({info['summary']}, {n_workers} parallel workers)..."
    )

    # Results need to be returned in original order, so we keep slots.
    results: list[dict | None] = [None] * len(clips)
    completed = 0

    def _task(idx: int, clip: dict):
        return idx, generate_single_clip(
            video_path, clip, output_dir,
            transcription, template, add_subtitles,
            hook_position, sub_position,
            anticopy_strength=anticopy_strength,
            quality=quality,
        )

    failed = 0
    split_count = 0

    with ThreadPoolExecutor(max_workers=n_workers) as ex:
        futures = [
            ex.submit(_task, i, clip)
            for i, clip in enumerate(clips)
        ]

        for fut in as_completed(futures):
            try:
                idx, result = fut.result()
            except Exception as e:  # noqa: BLE001
                idx, result = -1, None
                emit_progress("generate", -1, f"Clip worker exception: {e}")

            completed += 1
            if result is not None:
                results[idx] = result
                if result.get('is_split_screen'):
                    split_count += 1
            else:
                if 0 <= idx < len(clips):
                    fallback = dict(clips[idx])
                    fallback['generated'] = False
                    fallback['error'] = 'FFmpeg processing failed'
                    results[idx] = fallback
                failed += 1

            pct = int((completed / max(len(clips), 1)) * 100)
            emit_progress(
                "generate", pct,
                f"Generated {completed}/{len(clips)} clips ({failed} failed)..."
            )

    generated = [r for r in results if r is not None]
    succeeded = sum(1 for r in generated if r.get('generated'))

    emit_progress(
        "generate", 100,
        f"Done! {succeeded}/{len(clips)} clips ({split_count} split-screen, {failed} failed)"
    )
    emit_complete("generate", {
        "total": len(clips),
        "success": succeeded,
        "failed": failed,
        "split_screen": split_count,
        "output_dir": output_dir,
    })

    # Save final clips metadata
    clips_json_path = os.path.join(output_dir, "clips.json")
    with open(clips_json_path, 'w', encoding='utf-8') as f:
        json.dump(generated, f, ensure_ascii=False, indent=2)

    return generated


if __name__ == "__main__":
    if len(sys.argv) < 4:
        print(json.dumps({
            "error": "Usage: python clip_generator.py <video_path> <clips.json> <video_id> [transcription.json] [template]"
        }))
        sys.exit(1)

    video_path = sys.argv[1]
    clips_path = sys.argv[2]
    video_id = sys.argv[3]

    with open(clips_path, 'r', encoding='utf-8') as f:
        clips = json.load(f)

    transcription = None
    if len(sys.argv) > 4 and os.path.exists(sys.argv[4]):
        with open(sys.argv[4], 'r', encoding='utf-8') as f:
            transcription = json.load(f)

    template = sys.argv[5] if len(sys.argv) > 5 else "default"

    result = generate_all_clips(video_path, clips, video_id, transcription, template)
    if not result:
        sys.exit(1)
